// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/libs3.h"
#include <Rcpp.h>

using namespace Rcpp;

// S3_init
void S3_init(const char* host);
RcppExport SEXP RS3_S3_init(SEXP hostSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char* >::type host(hostSEXP );
        S3_init(host);
    }
    return R_NilValue;
END_RCPP
}
