// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// S3Connect
void S3Connect(const char* host, const char* access_key, const char* secret_key);
RcppExport SEXP RS3_S3Connect(SEXP hostSEXP, SEXP access_keySEXP, SEXP secret_keySEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char* >::type host(hostSEXP );
        Rcpp::traits::input_parameter< const char* >::type access_key(access_keySEXP );
        Rcpp::traits::input_parameter< const char* >::type secret_key(secret_keySEXP );
        S3Connect(host, access_key, secret_key);
    }
    return R_NilValue;
END_RCPP
}
// test_bucket
void test_bucket();
RcppExport SEXP RS3_test_bucket() {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        test_bucket();
    }
    return R_NilValue;
END_RCPP
}
// create_bucket
void create_bucket();
RcppExport SEXP RS3_create_bucket() {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        create_bucket();
    }
    return R_NilValue;
END_RCPP
}
