# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S3Connect <- function(access_key, secret_key) {
    invisible(.Call('RS3_S3Connect', PACKAGE = 'RS3', access_key, secret_key))
}

test_bucket <- function(bucketName) {
    invisible(.Call('RS3_test_bucket', PACKAGE = 'RS3', bucketName))
}

create_bucket <- function(bucketName, acl = "private") {
    .Call('RS3_create_bucket', PACKAGE = 'RS3', bucketName, acl)
}

delete_bucket <- function(bucketName) {
    invisible(.Call('RS3_delete_bucket', PACKAGE = 'RS3', bucketName))
}

list_bucket <- function(bucketName, prefix = "", allDetails = 0L) {
    .Call('RS3_list_bucket', PACKAGE = 'RS3', bucketName, prefix, allDetails)
}

delete_object <- function(bucketName, key) {
    .Call('RS3_delete_object', PACKAGE = 'RS3', bucketName, key)
}

put_object <- function(bucketName, storage_location, filename) {
    .Call('RS3_put_object', PACKAGE = 'RS3', bucketName, storage_location, filename)
}

copy_object <- function(sourceBucketName, sourceKey, destinationBucketName, destinationKey) {
    .Call('RS3_copy_object', PACKAGE = 'RS3', sourceBucketName, sourceKey, destinationBucketName, destinationKey)
}

get_object <- function(bucketName, key, filename = 0L) {
    .Call('RS3_get_object', PACKAGE = 'RS3', bucketName, key, filename)
}

